### PR TITLE
final setup

### PR DESCRIPTION
**Pull request by hetrox8**
This branch's core goal is to 
Implement a connection between a Ruby on Rails back-end and React front-end.
Understand the pros and cons of different approaches of connecting Ruby on Rails back-end with React front-end.

### CODE REVIEW

**Comment by ShadyShawkat** [comment]
## Hi @hetrox8, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a professional readme.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by Whoistolu — CHANGES_REQUESTED** [review]
Hi @hetrox8 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ]  _Check the inline comments under the review for sections to improve._
- [ ] [REQUIRED] NB: I am adding this recommendation here because the models directory and file `message.rb`  is not  added to the file changes. While using `Message` might work, using a more specific name like `Greeting` is often preferred. I can see that your controller name is `greetings_controller` and also in your migration, you created a `greetings` table. So, your model name should be `Greeting`. This will help in adhering to Rails conventions, reduce potential confusion, and make your code more self-explanatory.
- Considering the provided project requirements and the Rails conventions, it's recommended to use `Greeting` as the model name.

### Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

### N/A

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by hetrox8** [comment]
## changes made
1. Rename models

**Review by Shedrack-Sunday — APPROVED** [review]
Hi @hetrox8     👍 
Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

image


Highlights
- [x] Good project organization ✔️
- [x] Nice use of Rails  features  ✔️  
- [x] Kudus on meeting the requirements as pointed the last time out by the last reviwer  👏 



Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Pull request merged**
